### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mjkki** [rezkyws/cnn-nsfw#1]
I want to know which dataset you used,thanks

**Comment by rezkyws** [comment]
Hi, i just checked the dataset again in Kaggle, it seems they already removed the dataset. Fortunately, I already downloaded and save it to my gdrive

Please, drop your email here or send an email privately to my email account, so i can send the link to you. Thanks

**Comment by mjkki** [comment]
My email address is  yinwq887@163.com ，thanks :)

**Comment by rezkyws** [comment]
ok, check your email
